### ISSUE TITLE
Brand ID in the wrong place

### ISSUE THREAD

**Issue by dgoring** [docusign/docusign-php-client#111]
if you go by this https://developers.docusign.com/esign-rest-api/code-examples/brands-sending-envelope

The brand id is assigned to the individual signer not the entire envelope.

the brand_id setters and getters need to been moved from the EnvelopeDefinition model to the Signer model.

**Comment by LarryKlugerDS** [comment]
A brand_id is assigned to the envelope definition, not to the signer object.

You've spotted a bug in the bash example, thank you! The other examples correctly show the brand_id as part of the envelope definition.

I have filed internal ticket DEVDOCS-3130

Regards,
Larry

**Comment by dgoring** [comment]
No I've tested this and it works when the brand_id is put as part Signer Model

It does nothing when you assign it to the envelope, the bash is correct to API and the PHP is wrong

**Comment by LarryKlugerDS** [comment]
Hmmm, interesting. I will look into it further. 
I've re-opened the issue.

**Comment by LarryKlugerDS** [comment]
One of our engineers has tested this and his results show that the `brandId` is part of the envelope definition, not the signer definition. This is also confirmed by the Swagger file. 

Additional attributes are ignored by DocuSign, so placing a brandId in the signer object will have no affect. 
Thanks,
Larry
