### ISSUE TITLE
Docusign - Unable to get signatureimage from the envelope created by android

### ISSUE THREAD

**Issue by sukhdevsmartdata** [docusign/docusign-php-client#118]
Hi there,
I am using this rest API to get signatureimage from the envelope
**Api Documentation:** https://developers.docusign.com/docs/esign-rest-api/reference/Envelopes/Envelopes/getRecipientSignatureImage/

And I am getting signature image from envelopes which are created by Web & IOS but for android's Envelope api is throwing this error

**{
    "errorCode": "RESOURCE_NOT_FOUND",
    "message": "The URL provided does not resolve to a resource."
}**

Also when I hit the API to get recipients data for envelopes, roleName is missing in Android's Envelope. I am not sure if missing rolename has relation to this issue but I am not getting signature image in case of android. Below is the API result of IOS & Android

**Api Documentation:** https://developers.docusign.com/docs/esign-rest-api/reference/Envelopes/EnvelopeRecipients/list/

**Android**

{
    "signers": [],
    "agents": [],
    "editors": [],
    "intermediaries": [],
    "carbonCopies": [],
    "certifiedDeliveries": [],
    "inPersonSigners": [
        {
            "hostName": "Narbhit Singh",
            "hostEmail": "developer.narabhit@gmail.com",
            "signerName": "Vishal",
            "signerEmail": "vishal.kushw@gmail.com",
            "creationReason": "sender",
            "requireUploadSignature": "false",
            "recipientId": "1",
            "recipientIdGuid": "2ff99a48-8494-4e5e-ba04-fbd940ed83e9",
            "requireIdLookup": "false",
            "userId": "34b3768e-615f-4ffb-887e-93b8879e73a9",
            "clientUserId": "864f43be-e329-4daf-b03d-21735109af5b",
            "routingOrder": "1",
            "status": "completed",
            "completedCount": "1",
            "signedDateTime": "2020-09-24T13:02:39.3930000Z",
            "deliveredDateTime": "2020-09-24T13:02:39.3930000Z",
            "deliveryMethod": "offline",
            "recipientType": "inpersonsigner"
        }
    ],
    "seals": [],
    "witnesses": [],
    "recipientCount": "1",
    "currentRoutingOrder": "1"
}

**IOS**
{
    "signers": [],
    "agents": [],
    "editors": [],
    "intermediaries": [],
    "carbonCopies": [],
    "certifiedDeliveries": [],
    "inPersonSigners": [
        {
            "hostName": "Narabhit Singh",
            "hostEmail": "developer.narabhit@gmail.com",
            "signerName": "Kiran Thakur",
            "signerEmail": "",
            "canSignOffline": "false",
            "creationReason": "sender",
            "requireUploadSignature": "false",
            "recipientId": "1",
            "recipientIdGuid": "6a8a8e8c-d459-41e2-ae69-05a7b3759eb7",
            "requireIdLookup": "false",
            "userId": "9befdcd7-cb7c-490b-983a-1a46a2ddaf1f",
            "routingOrder": "1",
            "note": "",
            "roleName": "Signer1",
            "status": "completed",
            "completedCount": "1",
            "signedDateTime": "2020-09-18T11:44:23.8200000Z",
            "deliveredDateTime": "2020-09-18T11:43:35.9000000Z",
            "deliveryMethod": "email",
            "recipientType": "inpersonsigner"
        }
    ],
    "seals": [],
    "witnesses": [],
    "recipientCount": "1",
    "currentRoutingOrder": "1"
}

can anybody help me with me this? I really searched for 3 days but couldn't get any success. Thanks in advance.

**Comment by dbbrahmbhatt** [comment]
Hi @sukhdevsmartdata. Thanks for reporting the issue. I see that android envelope is signed offline ("deliveryMethod": "offline") where as IOS envelope is signed via email. Are you getting this issue in android envelope which has "deliveryMethod": "email"? Also, Can you please post the your code snippet which you are using for fetching android envelope's signature image?

**Comment by LarryKlugerDS** [comment]
Next step for these issues is to provide an API log of the request/response. 
See [API logging](https://support.docusign.com/en/guides/ndse-user-guide-api-request-logging)

Also, since this is not an issue with the SDK itself, please ask as a question on StackOverflow with tag `docusignapi`

Thank you.
