### ISSUE TITLE
Issue with Composer v2

### ISSUE THREAD

**Issue by tcov189** [docusign/docusign-php-client#123]
After installing or updating with Composer 2, classes under the `\DocuDign\eSign` namespace cannot be found. 

Reverting back to Composer 1 resolves issue.

Please update to make compatible with Composer 2.

**Comment by LarryKlugerDS** [comment]
Thank you for the problem report! I have filed internal request  DCM-4854.

**Comment by tcov189** [comment]
@LarryKlugerDS Hello, I was wondering if there was any update or time frame on this?

**Comment by LarryKlugerDS** [comment]
I have now escalated the issue. I will also bring it up in the VP's meeting next week. 
A Pull Request would be very helpful for moving this along. 
Thank you

**Comment by tcov189** [comment]
I think what needs to happen to get this to work is that the files that contain multiple class definitions need to be abstracted out into their own classes. 

I was going to make a PR for this, but I noticed that all of the files are generated by swagger-codegen and wasn't sure if that would just recreate the single file multi class definitions again.

**Comment by LarryKlugerDS** [comment]
Aah, got it. You're correct about Swagger CodeGen, we'll need to update its templates. So please don't do a PR.
Thanks for the investigation.

**Comment by LarryKlugerDS** [comment]
Please connect with me on LinkedIn: https://linkedin.com/in/larrykluger

**Comment by tcov189** [comment]
@LarryKlugerDS I was wondering if there were any updates on this?

**Comment by LarryKlugerDS** [comment]
Update: I will be emphasizing the importance of this issue in a meeting with the VP and engineering group this evening

**Comment by LarryKlugerDS** [comment]
Related information from https://github.com/docusign/code-examples-php/issues/14 
From https://github.com/DylanGD

> Please remove hirak/prestissimo dependency, composer v2 does not support it and it's not more really necessary.
> ![Alt Text](https://user-images.githubusercontent.com/5663375/98745806-8822ce80-23b4-11eb-8aa2-121035af89fc.png)

**Comment by LarryKlugerDS** [comment]
The engineer working on this issue updated his composer to v2 and then loaded https://github.com/docusign/code-examples-php

He reports that there were no problems.

Can you provide a concise reproducible test case that fails with Composer v2? Thank you!

**Comment by tcov189** [comment]
@LarryKlugerDS I created a fork and added a test file 
https://github.com/tcov189/docusign-php-client/blob/composer-2-compatibility/test.php

Let me know if this is not a sufficient test and I can expand.

**Comment by LarryKlugerDS** [comment]
Great, thank you @tcov189 .

**Comment by dbbrahmbhatt** [comment]
Hi @tcov189 thanks for reporting the issue and sending the test file. Our swagger-spec is common for all the languages and classes are generated based on the swagger-spec. Changing it might create problem in all other SDKs. So the best solution to resolve this issue is to add the classmap in autoload of your composer.json file. 

`"autoload": {
        "classmap": [
            "vendor/docusign/esign-client/src"
        ]
    }`

I tested that with the test file you provided and it is working fine for both the versions of composer. Let us know if you still face the issue.

**Comment by tcov189** [comment]
I will try this and let you know if I still get an issue. Thanks for looking into it.

**Comment by LarryKlugerDS** [comment]
Hi @tcov189 -- sounds like the suggestion solved the problem.  I will ask the engineer to update the Readme file.
/Larry
