### ISSUE TITLE
Error HTTPS_REQUIRED_FOR_CONNECT_LISTENER

### ISSUE THREAD

**Issue by wehostadm** [docusign/docusign-php-client#131]
Hi,

Since few days, I had an error when creating a recipient view for DocuSign. Nothing has changed in my code, I don't understand the issue.

The error is : 
_[critical] Uncaught PHP Exception DocuSign\eSign\Client\ApiException: "Error while requesting server, received a non successful HTTP code [400] with response Body:  O:8:"stdClass":2:{s:9:"errorCode";s:35:"HTTPS_REQUIRED_FOR_CONNECT_LISTENER";s:7:"message";s:50:"HTTPS required for Connect listener communication.";}" at /app/vendor/docusign/esign-client/src/Client/ApiClient.php line 344_

It seems that we should now use an https request.

The code that create the view is (I use Symfony) :
`$returnUrl = $this->generateUrl("onboarding_contract", 
                ["token" => $token],
                UrlGeneratorInterface::ABSOLUTE_URL
            );`
               
`$viewRequest = new RecipientViewRequest([
                "authentication_method" => "none",
                "client_user_id" => $clientUserId,
                "return_url" => $returnUrl,
                "user_name" => $fullName, 
                "email" => $email
            ]);`

`$results = $envelopeApi->createRecipientView($envelopId, $viewRequest);`
            
`return [$envelopId, (isset($results['url']) ? $results['url'] : null)];`

Can you help me ?

Thanks,

**Comment by LarryKlugerDS** [comment]
It's not the RecipientViewRequest that is causing the error, it is your create envelope call.

You're including an eventNotification attribute that is using a url that starts with http. It needs to start with https. 

See this [StackOverflow answer](https://stackoverflow.com/questions/66064133/docusign-error-https-required-for-connect-listener/66082555#66082555)

I'm sorry this was breaking change for you.

**Comment by wehostadm** [comment]
Thanks, it works now
