### ISSUE TITLE
Syntax error in FoldersAPI, line 321

### ISSUE THREAD

**Issue by kunxin-chor** [docusign/docusign-php-client#22]
Error message:
`syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in C:\Users\Kun\Documents\octesys\vendor\docusign\esign-client\src\Api\FoldersApi.php on line 321`

`list` is a PHP reserved keyword; it can't be used as a method name unless you're running PHP 7.

**Comment by mkardakov** [comment]
exactly. I have the same issue

**Comment by gsnavin** [comment]
This method has been renamed to "listItems" with the latest version released.
