### ISSUE TITLE
Missing resend_envelope parameter for /v2/accounts/{accountId}/envelopes/{envelopeId}/recipients endpoint

### ISSUE THREAD

**Issue by OlexandrPopov** [docusign/docusign-php-client#25]
At present there is no way to set `resend_envelope` paramter in the \DocuSign\eSign\Api\EnvelopesApi::updateRecipients method. However the parameter is described in the [documentation](https://www.docusign.com/p/RESTAPIGuide/RESTAPIGuide.htm#REST%20API%20References/Modify%20or%20Correct%20and%20Resend%20Recipient%20Information.htm?Highlight=resend_envelope)

**Comment by OlexandrPopov** [comment]
As I understand it should be added in the same way as it's done for `\DocuSign\eSign\Api\EnvelopesApi::update` method. So, the declaration of the method will look like this:

`public function updateRecipients($account_id, $envelope_id, $recipients = null, EnvelopesApi\UpdateOptions $options = null)`

And the following code should be added to the method's body:

```
if ($options != null) {
    // query params
        
    if ($options->getResendEnvelope() !== null) {
        $queryParams['resend_envelope'] = $this->apiClient->getSerializer()->toQueryValue($options->getResendEnvelope());
    }
}
```

**Comment by gsnavin** [comment]
@OlexandrPopov Thanks for pointing this out. I understand the documentation for the API here is a bit miss leading but unfortunately you cannot use the updateRecipients to resend envelope existing recipients. You have to use the \DocuSign\eSign\Api\EnvelopesApi::update to resend envelopes for now. Will work with the documentation team to update it accordingly.

**Comment by OlexandrPopov** [comment]
@gsnavin Could you please describe why it can't be used in that way in more detail or provide a link to the documentation where it's described? Since our project is live now I have to substantiate to the project owner that something isn't appropriate anymore and needs to be reworked. Thanks in advance.
