### ISSUE TITLE
ObjectSerializer opens SplFileObject with write-only permissions

### ISSUE THREAD

**Issue by trickeyone** [docusign/docusign-php-client#36]
The ObjectSerializer opens the SplFileObject instance with write-only permissions. This makes doing any further operations on the file very difficult and usually requires re-opening the SplFileObject with a new instance.

If would be beneficial is the new instance of SplFileObject was changed from (ObjectSerializer:265):
```php
$deserialized = new \SplFileObject($filename, "w");
```
to
```php
$deserialized = new \SplFileObject($filename, "w+");
```

Making it capable of rewinding and reading from the same SplFileObject instance.

**Comment by gsnavin** [comment]
@trickeyone Thanks for bring this our attention, we will review this internally and make the change is we deem necessary. Until then please try reopening the file with a new instance for other operations.
Sorry for the inconvenience.
