### ISSUE TITLE
Class '\DocuSign\eSign\Model\DateTime' not found

### ISSUE THREAD

**Issue by benburleson** [docusign/docusign-php-client#38]
Using the `TemplatesApi` `get()` method, it's failing on deserialize with the error trying to find the `\DocuSign\eSign\Model\DateTime` class (which does not exist, as far as I can tell).

Is there something I can do to fix this? Is this somehow dependent on my template data?

**Comment by theBull** [comment]
have you tried doing something like:

`use DocuSign\eSign\Model\DateTime` at the top of your .php file and then using the class as such in your code:

`new DateTime()` ?

**Comment by benburleson** [comment]
It's not my PHP file, it's the docusign library. There seems to be some history of that class existing at some time, but I can't tell if it was deprecated and they never cleaned up a reference to it or what.

I was hoping someone from Docusign would know, but they are surprisingly silent here in their own repo.
