### ISSUE TITLE
EnvelopesAPI getDocument method signature order change in v3

### ISSUE THREAD

**Issue by astridblahblahblah** [docusign/docusign-php-client#39]
The order for `$document_id` and `$envelope_id` has changed for EnvelopesApi->getDocument between versions:

V2
`public function getDocument($account_id, $envelope_id,  $document_id)`

V3
`public function getDocument($account_id, $document_id, $envelope_id, EnvelopesApi\GetDocumentOptions $options = null)`

Any particular reason why these two have been interchanged? Please let me know if this wasn't intentional and I can create a pull request for the fix.

Thanks.

**Comment by gsnavin** [comment]
@astridblahblahblah Thanks for pointing it out. Parameters in the swagger spec that we use to generate the php-client itself have been moved around. I will follow up on this issue internally and make the necessary changes. I would recommend you update your calls if that is a blocker for now. Sorry for the inconvenience.
