### ISSUE TITLE
Class EnvelopesApi\CreateEnvelopeOptions() Not found with composer 

### ISSUE THREAD

**Issue by optii** [docusign/docusign-php-client#42]
Hi,

I'm posting this here, but it could be composer related. Including the docusign eSign client via composer on a fresh Syfmony 3 install was giving me an error of:

```
Class EnvelopesApi\CreateEnvelopeOptions() not found
```

Despite the fact that the class was correctly spelled. (Copied from another working project). Changed composer version to the same that was used on the other project with no avail.  Removed all vendors and .lock file, with compose clear-cache and did a fresh install, the problem persisted.  (on both versions of composer)

Composer version 1.3.1 & 1.4.3 same issues.

All other Docusign Classes where autoloaded correctly.

Finally got it working using: 

```
composer dump-autoload --optimize
```

Please let me know what other information could be required for debugging ? or if this should be directed to composer

**Comment by LarryKlugerDS** [comment]
I apologize for the very slow reply to your issue. 

Is this still an issue?

Thanks,
Larry

**Comment by optii** [comment]
Hi, I'm no longer using this library so I could not say if it is still an issue or not.

**Comment by LarryKlugerDS** [comment]
Ok, thank you.
