### ISSUE TITLE
Creating Embed Request Sample

### ISSUE THREAD

**Issue by blacksage21** [docusign/docusign-php-client#43]
Is there somewhere i can find sample code for creating an Embedded Signing request using the SDK? 
This of course using a file not a template. Preferably using a link to the file and not the base64 content

**Comment by gsnavin** [comment]
@blacksage21 
Unfortunately you cannot specify a link to a file, have to send an envelope using base64 only.

Here are the links to  example code to request embedded sending/signing

Sending:
https://github.com/docusign/docusign-php-client/blob/master/test/UnitTests.php#L283

Signing:
https://github.com/docusign/docusign-php-client/blob/master/test/UnitTests.php#L303
