### ISSUE TITLE
Requirements say only PHP 5.3+ is required, but PHP 5.4 or possibly higher is actually required.

### ISSUE THREAD

**Issue by dqhendricks** [docusign/docusign-php-client#47]
Was trying to run this on a server with PHP 5.3.5, since the requirements on this page say PHP 5.3+ is required. I kept getting an internal server error when trying to run the example code. After poking around in the internals, I noticed that one of the files was using short hand array instantiation:

`$var = [];`

Short hand array instantiation was not introduced to PHP until version 5.4, and that is why I was getting an internal server error while running the example code. I am not sure if there are other features used in the SDK that would push the PHP version requirement even higher, but I can say for sure that at least version 5.4 or higher is required.

**Comment by gsnavin** [comment]
@dqhendricks Thanks for pointing it out. We have updated the README accordingly.
