### ISSUE TITLE
Update project on packagist 

### ISSUE THREAD

**Issue by fvozar** [docusign/docusign-php-client#49]
Currently composer installs v3.0.0 version with syntax error fixed in v3.0.1. Please publish new version.

**Comment by northern** [comment]
Hi there. Can we please do this? It appears that bugs have been fixed but if Packagist isn't synced, no one will receive the latest version.

https://packagist.org/packages/docusign/esign-client

Thanks!

**Comment by gsnavin** [comment]
This has been fixed. Sorry for the delay.
