### ISSUE TITLE
Send document for signing example

### ISSUE THREAD

**Issue by irufus** [docusign/docusign-php-client#50]
Is there an example that shows how to send a document for signing?

**Comment by irufus** [comment]
If anyone comes across this situation I figured it out. What you have to do is add the document object to the envelope_definition. Also there is no TemplateId to set as the API will reject your request.

**Comment by LarryKlugerDS** [comment]
We now have a complete set of examples. See the repository [eg-03-php-auth-code-grant](https://github.com/docusign/eg-03-php-auth-code-grant)
