### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by bhps69** [docusign/docusign-php-client#51]
Can we have any return statements to have some thing to believe to say this worked and the request has been sent. also in the test case, i encounter the same issue.

**Comment by LarryKlugerDS** [comment]
I apologize for the very slow response to your question. We have reorganized so questions will be answered sooner.

Regarding return values: The SDK's methods return the response object defined by the underlying DocuSign eSignature REST API. In most cases, there is a return value.  For example, the createEnvelope call returns the envelopeId and related information.

For methods that don't have a return object, the fact that the method returned without an error being thrown is your indication that the method succeeded.
