### ISSUE TITLE
How to use the updateProfileImageWithHttpInfo function?

### ISSUE THREAD

**Issue by juanvillegas** [docusign/docusign-php-client#52]
Trying to update a profile image for a User using the api, found this function but can really figure out how to use it to send the profile picture? The documentation here is also not clear: https://docs.docusign.com/esign/restapi/Users/Users/updateProfileImage/

I understand I should PUT the image, but under which name is the API expecting it?

Regarding the SDK, I can see there are two variables for the httpBody (function is declared here: https://github.com/docusign/docusign-php-client/blob/master/src/Api/UsersApi.php#L3062):

- $formParams: which is declared inside the function as an empty array.. thus its always empty.
- and $_tempBody, which is never declared thus isset($_tempBody) is always false.

See here for a reference of the above: https://github.com/docusign/docusign-php-client/blob/master/src/Api/UsersApi.php#L3106

Any ideas?

**Comment by LarryKlugerDS** [comment]
I apologize for the slow response to questions and issues. We have reorganized to give you responses sooner.

Please advise if this is still an open issue for you.

Thank you,
Larry

**Comment by juanvillegas** [comment]
Hey Larry, thanks for your answer. I'm no longer participating in that project so I'm gonna close the thread now.

Best,
Juan
