### ISSUE TITLE
V2 Fatal Error when resending envelope

### ISSUE THREAD

**Issue by decadeofdefeat** [docusign/docusign-php-client#55]
My environment is currently limited to PHP 5.5.9 so I'm attempting to put V2 of this software into production. (Composer requires 5.5.36 to install v3).

When I attempt to resend an envelope, I run into errors with ObjectSerializer:
```
$envelopeApi = new DocuSign\eSign\Api\EnvelopesApi($apiClient);

$updateOptions = new DocuSign\eSign\Api\EnvelopesApi\UpdateOptions();
$updateOptions->setResendEnvelope("true");

$update_summary = $envelopeApi->update($account_id, $env_id, $updateOptions);
```
```
PHP Fatal error:  Access to undeclared static property: DocuSign\eSign\Api\EnvelopesApi\UpdateOptions::$swaggerTypes in .../vendor/docusign/esign-client/src/ObjectSerializer.php on line 68
```

Any help would be appreciated!

**Comment by decadeofdefeat** [comment]
Nevermind, I forgot to pass an empty Envelope model.

**Comment by Crysalist** [comment]
> 

@decadeofdefeat can you elaborate on how exactly you did it?

**Comment by decadeofdefeat** [comment]
This happened so long ago that I honestly don't remember.

**Comment by Crysalist** [comment]
Finally found it - the body cannot be null you need to replace it with "{}"
so in the end it looked something like this: 
`$update_summary = $envelopeApi->update($account_id, $env_id, "{}", $updateOptions);`
