### ISSUE TITLE
Use of reserved word List for Model

### ISSUE THREAD

**Issue by td234** [docusign/docusign-php-client#58]
I am sure I am not the first to encounter this, but I was unable to find a solution while Googling.

I am trying to add a drop-down list to my document. At the top of my model I am adding these namespaces:

`use \DocuSign\eSign\Model\List;
use \DocuSign\eSign\Model\ListItem;
`
When doing so I get this error because "List" is a reserved word in PHP.

`A PHP Error was encountered

Severity: Parsing Error
Message:  syntax error, unexpected 'List' (T_LIST), expecting identifier (T_STRING)
Filename: models/Docusign_model.php
Line Number: 19
`
I tried changing the name of the class from "List" to "Elist" but then I got errors from ObjectSerializer that it could not find Elist:swaggerType.

What am I missing on how to add a list to my document?

Thom

**Comment by MichaelElementary** [comment]
@td234  I have also just run into this issue
The problem is that this SDK is not compatible with PHP5.4 as the repos would have you believe.
List is reserved word before PHP7 and cannot be used in namespaces and class definitions

You'll need to upgrade PHP on your server

**Comment by rfc12399** [comment]
All I have this exact same issue, but I am running PHP 7.1:

$tt_state = new \DocuSign\eSign\Model\List();
$tt_state->setTabLabel("state");
$tt_state->setValue($sign_data['p_state']);

[11-Sep-2018 15:38:54 America/New_York] PHP Parse error:  syntax error, unexpected 'List' (T_LIST), expecting identifier (T_STRING) in C:\inetpub\wwwroot\allstardriveredonline_new\docusign\create_envelope.php on line 131

Any ideas?  I did the same and tried to rename the class 'ListX()' but the ObjectSerializer threw errors...

**Comment by arvenom** [comment]
same issue here

**Comment by rfc12399** [comment]
@arvenom  - I was working directly with Docusign's professional services team at the time of my last post and they ended up confirming that it was a defect in the PHP API and said they would fix it at some point, but I wouldnt hold your breathe waiting :)

**Comment by acooper4960** [comment]
We need to add custom logic in our swagger code gen tool to properly map this word. I have created an internal ticket for our team to address this.

**Comment by acooper4960** [comment]
The model \DocuSign\eSign\Model\ModelList, should be used in place of  \DocuSign\eSign\Model\List. This will c

**Comment by acooper4960** [comment]
The model \DocuSign\eSign\Model\ModelList, should be used in place of  \DocuSign\eSign\Model\List. This SDK prepends the word Model in front of models with keyword conflicts
