### ISSUE TITLE
testConfig vs TestConfig

### ISSUE THREAD

**Issue by Ohda** [docusign/docusign-php-client#59]
Hello,

You have a testConfig.php and a TestConfig.php inside the tests folder.
I may generate issues on windows/unix...

**Comment by danieldevsquad** [comment]
![image](https://user-images.githubusercontent.com/23129061/39640054-049415fa-4f87-11e8-8418-919a2baf927c.png)

**Comment by Si0n** [comment]
This must be resolved asap - can't install SDK on Ubuntu as a result of names conflict

**Comment by gsnavin** [comment]
Thanks @Ohda for the PR, I have merged it now.
