### ISSUE TITLE
I have a problem to autopopulate tabs for template

### ISSUE THREAD

**Issue by crocodile305** [docusign/docusign-php-client#63]
I'm trying to add some values to template tabs but not act correct.
This is my code snap.

 $templateRole = new DocuSign\eSign\Model\TemplateRole();
  $templateRole->setClientUserId($email);
  $templateRole->setEmail($email);
  $templateRole->setName($recipientName);
  $templateRole->setRoleName($templateRoleName);

  $textTab = new \DocuSign\eSign\Model\Text();

  $textTab->setTabLabel("Field Label");
  $textTab->setValue('Value');

  $tabs = new DocuSign\eSign\Model\Tabs();
  $tabs->setTextTabs(array($textTab));
  $templateRole->setTabs($tabs);

Please help me.

**Comment by acooper4960** [comment]
Hello, what part is not working correctly?

**Comment by LarryKlugerDS** [comment]
Closing due to no further request on the thread.
