### ISSUE TITLE
Cannot update a property to Null value

### ISSUE THREAD

**Issue by Ohda** [docusign/docusign-php-client#64]
When the SDK is calling the API for an update, only the properties that are set with a not null value are exported.
This lead to an issue => No way to update a property to a NULL value.

I was trying to switch an embded signer to remote by unsetting the user_client_id but i'am stuck.

**Comment by acooper4960** [comment]
are you able to work around this, ie. with an empty string?

**Comment by Ohda** [comment]
My workaround is : add a clone remote signer (with a routing_order+1 to avoid completed status) then delete the embded signer.
I will try to test how API with the empty string.
