### ISSUE TITLE
INVALID_REQUEST_BODY if I don't use `json_encode` on createEnvelope()

### ISSUE THREAD

**Issue by sentiasa** [docusign/docusign-php-client#65]
When trying to createEnvelope, it was throwing this error.
```
INVALID_REQUEST_BODY The request body is missing or improperly formatted. Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'API_REST.Models.v2.document[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\n ◀ To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive t ▶ Path 'documents.documentBase64', line 1, position 31.
```
After debugging, I figured out on [EnvelopesApi.php - L2876](https://github.com/docusign/docusign-php-client/blob/master/src/Api/EnvelopesApi.php#L2876), I had to wrap `json_encode($httpBody)`.

You can see my createEnvelope code here: https://stackoverflow.com/questions/52627314/docusign-cant-set-sent-on-createenvelope

Was I doing something wrong?

**Comment by acooper4960** [comment]
This appears to be answered on github. Was that solution sufficient?

**Comment by acooper4960** [comment]
This appears to be answered in stackoverflow, was that sufficient?

**Comment by sentiasa** [comment]
That's right - it was my mistake actually.
