### ISSUE TITLE
Populate Text Field - Api, PHP

### ISSUE THREAD

**Issue by salines** [docusign/docusign-php-client#66]
Hello,

- We created / upload template in appdemo
- We add text fields via admin interface
- we want to populate this text field when run php script (docusign-php-client) or using simple CURL scripts from api documentations.
- when run php script, we send email, but in document is not populated our text fields.

How to setup this php client to add our text in uploaded template?

SO:
https://stackoverflow.com/questions/52934613/how-to-post-text-to-template-using-php-sdk

**Comment by LarryKlugerDS** [comment]
Hi,
I apologize for the slow response. Is this still an issue for you?

You can set the values of tabs that are defined in a template when you create the envelope.

See [example 17](https://github.com/docusign/eg-03-php-auth-code-grant/blob/master/src/EG017SetTemplateTabValues.php) which does this.
