### ISSUE TITLE
Error installing with composer

### ISSUE THREAD

**Issue by martinolson** [docusign/docusign-php-client#69]
Failed to execute unzip -qq  '/Users/username/projects/vendor/docusign/esign-client/23a7f5708e3ef7cac0e30bbdabcc91fd' -d '/Users/username/projects/vendor/composer/73a8a353'

replace /Users/username/projects/vendor/composer/73a8a353/docusign-docusign-php-client-bf4c4af/test/testConfig.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

**Comment by jkofoedGC** [comment]
I have the same issue, any thoughts?

$ composer require docusign/esign-client
Using version ^3.0 for docusign/esign-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing docusign/esign-client (3.0.1): Loading from cache
    Failed to execute unzip -qq  '.../vendor/docusign/esign-client/b59b24bd90845c218cd1f264f69ca924' -d '.../vendor/composer/350189bf'

replace .../vendor/composer/350189bf/docusign-docusign-php-client-bf4c4af/test/testConfig.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
Writing lock file
Generating autoload files

**Comment by Ohda** [comment]
This has been fixed by : https://github.com/docusign/docusign-php-client/pull/61
But no new tag have been realeased.
Use master branch if you want the fix.

**Comment by LarryKlugerDS** [comment]
Thank you for the problem report. 
And thank you to @Ohda for the pull request.

I have started internal ticket DCM-3191 to have the fix processed.

**Comment by marksark** [comment]
I'm having this issue currently, has this fix been pushed?

**Comment by jkofoedGC** [comment]
@marksark Since they didn't release the fix you have to point your composer to the master branch.  On your composer file do: "docusign/esign-client": "master@dev"

**Comment by dbbrahmbhatt** [comment]
Issue has been resolved
