### ISSUE TITLE
Send Documents Using Bulk Send Example

### ISSUE THREAD

**Issue by nsaumini** [docusign/docusign-php-client#72]
Hi, Can anyone guide me on how to add bulk recipient to an envelope.

**Comment by LarryKlugerDS** [comment]
Hi @nsaumini,

Are you sure you want to use Bulk Send? It is often easier to just make a loop, sending one envelope after another.

If you do decide to use Bulk Send, see the instructions on the [BulkSend resource page.](https://developers.docusign.com/esign-rest-api/reference/BulkEnvelopes/BulkEnvelopes)

The actual sending is done via the [Envelopes::create](https://developers.docusign.com/esign-rest-api/reference/Envelopes/Envelopes/create) API / SDK method.

For relating programming questions, please use StackOverflow with tag "docusignapi".

Many thanks,
Larry
