### ISSUE TITLE
set custom field input for envelope

### ISSUE THREAD

**Issue by techtic-harshad** [docusign/docusign-php-client#75]
I have created custom field in docusign(Envelope Custom Fields) but not able to set it out using this package in Laravel, so can you please help me to figure it out.

$envelope_definition = new EnvelopeDefinition([ 'status' => "sent", 'composite_templates' => $compositeTemplate, 'custom_fields' => [ "text_custom_fields" => [ ["name" => "abcID", "value" => 11] ] ] ]); This is the code that may work but its not.

**Comment by LarryKlugerDS** [comment]
The EnvelopeDefinition includes the **customFields** attribute. I'd set your field there.
