### ISSUE TITLE
v4.0.0 Incorrect ApiException exception references

### ISSUE THREAD

**Issue by abarke** [docusign/docusign-php-client#78]
ApiException class was moved, however references/phpdocs throughout the code do not point to the new location.

e.g. 
\DocuSign\eSign\Client\ApiException is referenced in many places as \DocuSign\eSign\ApiException which my editor PHPStorm complains about it not existing.

I also noticed that the PHP code is not to PHP best practices in places. 
I would recommend using phpstan to scan the code: https://github.com/phpstan/phpstan

**Comment by abarke** [comment]
Here is the code analysis from PhpStorm:

I suggest a serious tidyup is needed. This is not production ready code in my eyes.

![image](https://user-images.githubusercontent.com/34715541/59765889-5846c880-929f-11e9-9623-4fc88aa78798.png)

![image](https://user-images.githubusercontent.com/34715541/59765804-27669380-929f-11e9-8bf2-9ee948c12873.png)

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. I have filed internal bug DCM-3372

Re: I also noticed that the PHP code is not to PHP best practices in places.
I would recommend using phpstan to scan the code: https://github.com/phpstan/phpstan

I have filed enhancement request DCM-3373

**Comment by LarryKlugerDS** [comment]
Hi @abarke ,
DocuSign engineering reports that this problem has been solved. Can you verify?
Many thanks,
Larry

**Comment by abarke** [comment]
Confirmed. Working with v5.0.0 and I dont see these errors anymore. Thanks.

**Comment by LarryKlugerDS** [comment]
Excellent, thank you
