### ISSUE TITLE
Class '\DocuSign\eSign\Model\OfflineAttributes' not found

### ISSUE THREAD

**Issue by robotdoug** [docusign/docusign-php-client#80]
When using the `EnvelopesApi::listRecipients` method, it fails during the deserialization process due to not being able to find `\DocuSign\eSign\Model\OfflineAttributes`.

Appears the class was present in v3, but has been removed in v4 of the library.

**Comment by LarryKlugerDS** [comment]
Thank you for the bug report. I have filed internal report DCM-3374

**Comment by robotdoug** [comment]
Hi @LarryKlugerDS, any idea when a fix for this will be implemented?

**Comment by LarryKlugerDS** [comment]
Hi @robotdoug , unfortunately there is no schedule yet. I have asked the product and engineering managers to consider it for an upcoming sprint. I will update this thread as I hear more.

**Comment by Krowemoh** [comment]
For now we commented out the lines referencing offline_attributes in models/in_person_signer.py, models/signer.py and models/witness.py

**Comment by LarryKlugerDS** [comment]
Thank you for the update. I appreciate your time.

**Comment by chaosaround** [comment]
Still facing the same problem with v5.0.0.

**Comment by LarryKlugerDS** [comment]
Hi, I am sorry that this hasn't been fixed yet. I have re-raised it to our engineering group with a cc to our vice president.

**Comment by LarryKlugerDS** [comment]
Hi, our engineering group requests that you check the latest release, version 5.1.0. 
Please let me know if the problem is also in that release.
Thank you,
Larry

**Comment by chaosaround** [comment]
Hi @LarryKlugerDS,
Works great with v5.1.0-rc
Thank you all!

**Comment by LarryKlugerDS** [comment]
Excellent, some good news. Thank you for your help.
