### ISSUE TITLE
Uncaught Error: Class 'DocuSign\\eSign\\ApiClient' not found

### ISSUE THREAD

**Issue by bbouchard95** [docusign/docusign-php-client#82]
To fix this change DocuSign\eSign\ApiClient($config); to DocuSign\eSign\Client\ApiClient($config);

**Comment by gsnavin** [comment]
@bbouchard95 Thanks for the recommending a fix. Can you please let us know which version of the SDK are you using. Also where exactly are you asking this to be changed?

**Comment by bbouchard95** [comment]
I'm using v4. I apologize, I just realized I should have issued this at https://github.com/docusign/qs-php instead of here. qs-01-php-embed-signing-ceremony.php and qs-02-php-send-envelope.php both produce this error. I'll copy this issue and bring it there.

**Comment by gsnavin** [comment]
@bbouchard95 thanks for the update.  I will close this issue from here.
