### ISSUE TITLE
ApiException#getResponseObject is now a serialized PHP object

### ISSUE THREAD

**Issue by nie7321** [docusign/docusign-php-client#83]
In v3.0.1, calling `ApiException#getResponseObject()` would return an `ErrorDetails` object:

![Screen Shot 2019-07-11 at 8 02 59 AM](https://user-images.githubusercontent.com/27235866/61053180-a63c8100-a3b2-11e9-967a-045c3e96d20d.png)

In the v4.0.0 release, this now returns a serialized PHP object as a string:

![Screen Shot 2019-07-11 at 7 56 21 AM](https://user-images.githubusercontent.com/27235866/61053215-c0765f00-a3b2-11e9-896b-68ace0d31d62.png)

The breaking changes section in the change notes do not mention this change, so I have to ask if it was intended or if this is a bug?

**Comment by nie7321** [comment]
The break looks like it is being caused by this new bit of code: https://github.com/docusign/docusign-php-client/blob/master/src/Client/ApiClient.php#L326

It was not present in v3.0.1: 

![Screen Shot 2019-07-11 at 8 16 47 AM](https://user-images.githubusercontent.com/27235866/61054001-421abc80-a3b4-11e9-806b-
d681e9b539d8.png)

**Comment by nie7321** [comment]
This isn't really a question. This is an undocumented breaking change.

**Comment by LarryKlugerDS** [comment]
Thank you for raising this issue. I have filed internal report DCM-3466. I will also ask for a new regression test to be added.

**Comment by dbbrahmbhatt** [comment]
Hi @nie7321  ,
we have fixed this for the forthcoming 5.5 release. Currently thats the 5.5.0-RC release -- RC means Release Candidate.

To install it: `composer require docusign/esign-client:v5.5.0-rc`

Please validate from your side and let us know if you still face the issue.

**Comment by LarryKlugerDS** [comment]
Fixed in v5.5. Please re-open if this is still an issue. Thank you
