### ISSUE TITLE
Checkbox $tabGroup->setMaximumAllowed('1') not working

### ISSUE THREAD

**Issue by abarke** [docusign/docusign-php-client#89]
Seems $tabGroup->setMaximumAllowed('1') is not working as expected. I can still select both checkboxes in the online signing ceremony.

I built this solution from this example on stackoverflow:
https://stackoverflow.com/a/58210277/11475075

```php
// Tab Group for linking the Checkboxes
$tabGroup = new TabGroup();
$tabGroup->setGroupLabel(self::CHECKBOX_GROUP);
$tabGroup->setGroupRule('SelectAtLeast');
$tabGroup->setMinimumRequired('0');
$tabGroup->setMaximumAllowed('1'); # this is not working!
$tabGroup->setValidationMessage('Please check one box should you wish to opt-in');
$tabGroup->setTabScope('Document');
$tabGroup->setPageNumber('7');
$tabGroup->setDocumentId('1');
$tabGroup->setRecipientId('2');
```

Output:

```json
"checkboxTabs": [
    {
        "documentId": "1",
        "pageNumber": "7",
        "recipientId": "2",
        "tabGroupLabels": [
            "CheckboxGroup"
        ],
        "tabLabel": "CheckBox Option 1",
        "xPosition": "80",
        "yPosition": "321"
    },
    {
        "documentId": "1",
        "pageNumber": "7",
        "recipientId": "2",
        "tabGroupLabels": [
            "CheckboxGroup"
        ],
        "tabLabel": "CheckBox Option 2",
        "xPosition": "80",
        "yPosition": "336"
    }
],
"tabGroups": [
    {
        "documentId": "1",
        "groupLabel": "CheckboxGroup",
        "groupRule": "SelectAtLeast",
        "maximumAllowed": 1,
        "pageNumber": "7",
        "recipientId": "2",
        "tabScope": "Document",
        "validationMessage": "Please check one box should you wish to opt-in"
    }
],
```

**Comment by LarryKlugerDS** [comment]
The possible `groupRule` values are `SelectAtLeast`, `SelectAtMost`, `SelectExactly`, `SelectARange`

**If you want a maximum of 1, then set `groupRule` to `SelectAtMost`**

The associated attributes are `minimumRequired`, `maximumAllowed`, as appropriate.

I have submitted Jira DEVDOCS-2087

**Comment by abarke** [comment]
Thanks @LarryKlugerDS I assume the `minimumRequired` option is taken into account if I set `groupRule` to `SelectAtMost` or could I use `SelectExactly` one to make sure the user must check a box, but only one box (radio).

**Comment by LarryKlugerDS** [comment]
No, I don't think that's right. If you want minimumrequired to be used in that way, you can't use selectatmost, use selectarange
