### ISSUE TITLE
Just sign frame in html page

### ISSUE THREAD

**Issue by jasminder** [docusign/docusign-php-client#96]
Hello, I just need the signature frame in the HTML form flow, just like Google Re Captcha get embedded in form. Is it possible anyway with Docusign / API. ?

**Comment by LarryKlugerDS** [comment]
Unfortunately, no. 

What you can do:

1. Create a template, then create a PowerForm, [intro](https://www.docusign.com/features-and-benefits/features/powerforms), [docs](https://support.docusign.com/en/guides/ndse-user-guide-using-powerforms), from it. Record the PowerForm's URL.
1. In your form, when the user clicks `Sign`, create a custom URL that includes query parameters. Use the query parameters to set the PowerForm's tab values. [Docs](https://docs.docusign.com/supportdocs/ndse-help/Content/populate-custom-fields.htm)

   You can create the customized URL either within the web page itself (using JavaScript), on on your server.
1. Redirect the user to the URL you've created. 
1. The PowerForm will then open, and the signer can sign the document that includes the values from your HTML form.
1. You can have the PowerForm redirect the user back to your app after they've signed. See [docs](https://support.docusign.com/en/articles/How-do-I-specify-a-URL-to-redirect-to-when-a-Powerform-is-completed).

An alternative is to use the DocuSign eSIgnature API to create a customized envelope and signing ceremony for your web visitor to sign.
